apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - command:
        - /opt/helloworld/bin/flask
        - run
        - -h
        - 0.0.0.0
        env:
        - name: FLASK_APP
          value: "helloworld.py"
        - name: FLASK_DEBUG
          value: "1"
        image: shtouff/helloworld:latest
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 5000
          name: flask-tcp-local
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /kinexistepas
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
