apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxyworld
  name: proxyworld
  namespace: staging
spec:
  type: NodePort
  ports:
  - name: flask
    port: 80
    protocol: TCP
    targetPort: 4000
    nodePort: 30400
  selector:
    app: proxyworld
