apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxyworld
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxyworld
  template:
    metadata:
      labels:
        app: proxyworld
    spec:
      containers:
      - command:
        - /opt/proxyworld/bin/flask
        - run
        - -h
        - 0.0.0.0
        - -p
        - "4000"
        env:
        - name: FLASK_APP
          value: "proxyworld.py"
        - name: FLASK_DEBUG
          value: "1"
        image: shtouff/proxyworld:v0.0.3
        imagePullPolicy: Always
        name: proxyworld
        ports:
        - containerPort: 4000
          name: flask-tcp-local
          protocol: TCP
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
